# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_parent', to='api.Group', verbose_name='Родительская группа'),
        ),
        migrations.AlterField(
            model_name='element',
            name='descr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='element',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_group', to='api.Group', verbose_name='Родительская группа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='descr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
